"use strict";

// Generated by CoffeeScript 2.3.2
var pad;
pad = require('./index');

module.exports = function (string, size) {
  var options = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : {};

  if (typeof options === 'string') {
    options = {
      char: options
    };
  }

  options.colors = true;
  return pad(string, size, options);
};