// Generated by CoffeeScript 1.7.1
var pad;

pad = require('./pad');

module.exports = function(string, size, options) {
  if (options == null) {
    options = {};
  }
  if (typeof options === 'string') {
    options = {
      char: options
    };
  }
  options.colors = true;
  return pad(string, size, options);
};
