// Generated by CoffeeScript 2.4.1
var color;

import pad from './index';

color = function(string, size, options = {}) {
  if (typeof options === 'string') {
    options = {
      char: options
    };
  }
  options.colors = true;
  return pad(string, size, options);
};

export default color;
